
export const genres: Record<string, string[]> = {
    "Drum and Bass": ["Autonomic", "Breakcore", "Choppage", "Clownstep", "Darkstep", "Drill 'n' bass", "Drumfunk", "Drumstep", "Dub-wise", "Future Bass", "Halftime", "Hardstep", "Intelligent D&B", "Jazzy Jungle", "Jump-Up", "Liquid Funk", "Metal & Bass", "Minimal D&B", "Neurofunk", "Neurohop", "Ragga Jungle", "Raggacore", "Sambass", "Techstep", "Trancestep"],
    "Dubstep": ["2-step garage", "Bassline", "Breakbeat hardcore", "Brostep", "Chillstep", "Darkstep", "Deathstep", "Drumstep", "Dubstyle", "Future Garage", "Glitch Hop", "Grime", "Hardstep", "Jump-up", "Jungle", "Liquid funk", "Melodic Dubstep", "Neurofunk", "Post-dubstep", "Riddim", "Sambass", "Techstep", "Trap (EDM)", "UK Dubstep (Original)", "Wonky"],
    "Electro/Breaks": ["2-step garage", "Acid Breaks", "Baltimore Club", "Bassline", "Big Beat", "Breakbeat", "Breakbeat hardcore", "Broken beat", "Chemical breaks", "Complextro", "Dutch House", "Electro House", "Electro-swing", "Fidget House", "Florida Breaks", "Grime", "Melbourne Bounce", "Miami Bass", "Moombahton", "Moombahcore", "Nu Skool Breaks", "Progressive Breaks", "Psychedelic breakbeat", "Twerk", "UK Funky"],
    "Experimental/IDM": ["Ambient", "Bitpop", "Chillwave", "Chiptune", "Deconstructed Club", "Drone", "Electroacoustic music", "Folktronica", "Glitch", "Hypnagogic pop", "Illbient", "Lo-fi hip hop", "Lowercase", "Musique concrète", "Nintendocore", "Noise", "Onkyo", "PC Music", "Psybient", "Seapunk", "Skweee", "Sound art", "Vaporwave", "Witch House", "Wonky"],
    "Hardstyle": ["Bouncy Techno", "Darkcore", "Early Hardstyle", "Euphoric Hardstyle", "Frenchcore", "Gabber", "Happy Hardcore", "Hard NRG", "Hard Trance", "Hardcore", "Industrial Hardcore", "J-core", "Jumpstyle", "Lento Violento", "Mákina", "Mainstream Hardcore", "New Beat", "Psystyle", "Rawstyle", "Scouse House", "Speedcore", "Tekstyle", "Terrorcore", "UK Hardcore", "Zombiestyle"],
    "Hip Hop": ["Alternative Hip Hop", "Boom Bap", "Cloud Rap", "Conscious Hip Hop", "Crunk", "Drill", "Emo Rap", "Experimental Hip Hop", "G-Funk", "Gangsta Rap", "Grime", "Hardcore Hip Hop", "Horrorcore", "Hyphy", "Industrial Hip Hop", "Jazz Rap", "Lo-Fi Hip Hop", "Mumble Rap", "Political Hip Hop", "Snap Music", "Soundcloud Rap", "Southern Hip Hop", "Trap", "Turntablism", "UK Drill"],
    "House": ["Acid House", "Afro House", "Balearic Beat", "Bass House", "Chicago House", "Deep House", "Electro Swing", "French House", "Funky House", "Garage House", "Ghetto House", "Hard House", "Hip House", "Italo House", "Latin House", "Lo-fi House", "Melodic House", "Microhouse", "Outsider House", "Progressive House", "Soulful House", "Speed Garage", "Tech House", "Tribal House", "Tropical House"],
    "Techno": ["Acid Techno", "Ambient Techno", "Berlin Techno", "Birmingham sound", "Bleep Techno", "Chiptune", "Dark techno", "Detroit Techno", "Dub Techno", "Freetekno", "Gabber", "Ghettotech", "Hardcore Techno", "Hardgroove", "Industrial Techno", "J-core", "Livetronica", "Melodic Techno", "Minimal Techno", "Nortec", "Peak Time Techno", "Raw/Hypnotic Techno", "Rotterdam techno", "Schranz", "Wonky techno"],
    "Trance": ["Acid Trance", "Balearic Trance", "Dark Psytrance", "Darkcore", "Dream Trance", "Euro-trance", "Forest Psy", "Freeform hardcore", "Full-On", "Goa Trance", "Hard Trance", "Hardstyle", "Hi-Tech", "Ibiza Trance", "Melodic Trance", "Nitzhonot", "Progressive Psy", "Progressive Trance", "Psybient", "Psytrance", "Suomisaundi", "Tech Trance", "UK hardcore", "Uplifting Trance", "Vocal Trance"]
};

export const moods: string[] = ["Abstract", "Adventurous", "Aggressive", "Airy", "Ancient", "Angry", "Anxious", "Aquatic", "Atmospheric", "Blissful", "Bouncy", "Calm", "Chaotic", "Cinematic", "Clean", "Cold", "Comical", "Complex", "Concrete", "Cosmic", "Crisp", "Dark", "Delicate", "Dirty", "Dreamy", "Driving", "Earthy", "Ecstatic", "Elegant", "Energetic", "Enigmatic", "Epic", "Ethereal", "Euphoric", "Exotic", "Fearful", "Fiery", "Flowing", "Funky", "Futuristic", "Glitchy", "Gloomy", "Graceful", "Grateful", "Gritty", "Groovy", "Happy", "Haunting", "Heavy", "Heroic", "Hopeful", "Hypnotic", "Industrial", "Introspective", "Jazzy", "Lazy", "Light", "Lush", "Majestic", "Mechanical", "Melancholic", "Mellow", "Minimalist", "Modern", "Mysterious", "Nostalgic", "Ominous", "Orderly", "Organic", "Peaceful", "Playful", "Polished", "Pounding", "Powerful", "Psychedelic", "Raw", "Rebellious", "Relaxed", "Restless", "Retro", "Romantic", "Rural", "Sad", "Sentimental", "Serene", "Serious", "Smooth", "Soulful", "Sparse", "Spiritual", "Stuttering", "Sublime", "Surprised", "Tense", "Tragic", "Trippy", "Uplifting", "Urban", "Vibrant", "Villainous", "Warm", "Whimsical"];

export const instruments: string[] = ["Accordion", "Acoustic Guitar", "Agogo Bells", "Alto Sax", "Bagpipes", "Balalaika", "Banjo", "Bansuri", "Baritone Sax", "Bass Guitar", "Bassoon", "Beatbox", "Bongos", "Bouzouki", "Brass Section", "Cajon", "Celeste", "Cello", "Chapman Stick", "Choir Aahs", "Choir Oohs", "Church Organ", "Clarinet", "Clavinet", "Congas", "Cowbell", "Didgeridoo", "Djembe", "Dobro", "Double Bass", "Drum Machine", "Drums (Acoustic)", "Dulcimer", "E-Bow Guitar", "Electric Guitar", "Electric Piano", "Fiddle", "Finger Snaps", "Flute", "French Horn", "Gamelan", "Glass Harmonica", "Glockenspiel", "Grand Piano", "Guiro", "Hammond B-3", "Hand Claps", "Hang Drum", "Harmonica", "Harp", "Harpsichord", "Kalimba", "Koto", "Lap Steel", "LinnDrum", "Lute", "Mandolin", "Marimba", "Melodica", "Mellotron", "Music Box", "Oboe", "Ondes Martenot", "Organ", "Orchestral Percussion", "Oud", "Pan Flute", "Pedal Steel", "Piano", "Recorder", "Rhodes Piano", "Sarod", "Saxophone", "Shaker", "Shamisen", "Sitar", "Solo Voice", "Soprano Sax", "Steel Drums", "String Section", "Tabla", "Taiko Drums", "Taikotron", "Talk Box", "Tambourine", "Tenor Sax", "Theremin", "Timpani", "TR-808", "TR-909", "Triangle", "Trombone", "Trumpet", "Tuba", "Uilleann Pipes", "Ukulele", "Upright Piano", "Vibraphone", "Viola", "Violin", "Vocoder", "Wood Block", "Wurlitzer", "Xylophone", "Zither"];

export const synths: string[] = ["8-bit Chiptune", "Absynth Atmospheric", "Acid Squleches", "Additive Synthesis", "Analog Hi-Hats", "Analog Kick Drum", "Analog Snare", "ARP 2600 FX", "Arpeggiated Chords", "Arturia Pigments Granular", "Berghain Rumble Kick", "Braam FX", "Brown Noise", "Buchla Easel", "Choral Pad", "Cinematic Pulse", "Color Bass", "Cross-Modulation FX", "CS-80 Vangelis", "Cyberpunk Lead", "Dark Synth Drone", "Deep House Pad", "Detuned Square Lead", "Distorted Lead", "Diva Analog Lead", "Donk Bass", "Drill Bass Glide", "Dub Techno Chord", "DX7 Electric Piano", "Ethereal Pad", "Eurorack Drone", "FM8 Bell Tone", "Filtered Saw Pad", "Formant/Vocal Synth", "Future Bass Chords", "Generative Sequence", "Glassy FM Pad", "Glitch Percussion", "Goa Trance Lead", "Granular Cloud", "Growl Bass", "Hardstyle Screech", "Hoover Stab", "Hybrid Strings", "Impact", "Juno-106 Pad", "Jupiter-8 Strings", "Karplus-Strong", "Korg M1 Piano", "LFO-modulated Bass", "Lo-fi Synth Keys", "Lush Ambient Pad", "Massive Wobble Bass", "Melodic Techno Arp", "Metallic Percussion", "Minimoog Bass", "Modular Synth FX", "Moog Mother-32 Seq", "Neuro Bass", "Noise Sweep FX", "OB-6 Pad", "Phase Distortion", "Physical Modeling", "Pink Noise", "Pluck Bass", "Progressive Pluck", "Prophet-5 Brass", "Psytrance Bass", "PWM Strings", "Reaktor Glitch", "Reese Bass", "Resonant Filter Sweep", "Riddim Bass", "Ring Modulator", "Riser", "Sample & Hold Texture", "Sequenced Bassline", "Serum Wavetable", "SH-101 Lead", "SID Chip Sound", "Sine Wave Sub Bass", "Spire Pluck", "Sub Drop", "Sub Phatty Bass", "Supersaw Lead", "Sylenth1 Supersaw", "Sync Lead", "Synthwave Bass", "TB-303 Acid Line", "Tech House Stab", "Tension Drone", "Trance Gate Pad", "Trap Lead", "U-He Zebra Pad", "Vaporwave Pad", "Vector Synthesis", "Wavestation Vector", "Wavetable Pad", "White Noise", "Zaps & Blips"];

export const NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];
export const PIANO_ROLL_OCTAVES = 4;
export const STEPS_PER_BAR = 8;
export const MIDI_NOTE_OFFSET = 36; // C2